### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by SatoriHoshiAiko** [chrislennon/lnbits-discord-bot#13]
Hi there,

I received an issue running npm start with the following output:

npm start

> discord-lnd-bot@1.0.0 start
> node index.js

/Volumes/X11/lnbits-discord-bot/node_modules/lodash.isequal/index.js:1267
        ('constructor' in object 
                                 

SyntaxError: Unexpected end of input
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1049:15)
    at Module._compile (node:internal/modules/cjs/loader:1084:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Volumes/X11/lnbits-discord-bot/node_modules/<u>ow</u>/dist/predicates/array.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)

Node.js v18.7.0

I am wondering if you have any thoughts as to why it is giving this.

Thanks

**Comment by SatoriHoshiAiko** [comment]
It highlights at Object<anonymous> ... node_modules/OW/dist/predicates/array.js:4:17

I am using as you see Node.js

Also, I am on macOS Monterey 12.1 and M1 Mac Mini processor. npm install ran basically clean with no issues. 

Using git checkout main

The file and underlined directory ow does indeed exist.

Something else is not adding up right but I am not yet sure how to locate the cause of this bug.

Thanks
